## Generate HTML images

In [2]:
import plotly.graph_objects as go
import numpy as np

In [109]:
# create some random data values
random_x=np.random.randint(1, 100, 500)
random_y=np.random.randint(1, 100, 500)

print(random_x[:10])
print(random_y[:10])


[84 52 53 32 31 50 16 71 60  5]
[69 69 51 78 54 91 59 74 70 61]


In [108]:
# and some random color values
random_colors=random_x*random_y
print(random_colors[:10])

[1656 2808  125 3015 2184  135 2365  650 4836  221]


In [103]:
# create the data trace
trace=go.Scatter(
    x = random_x,
    y = random_y,
    mode='markers',
    marker=dict(
        size=12,
        color=random_colors, # set color equal to a variable
        colorscale=['blue',  'red', 'yellow'], # one of plotly colorscales
        showscale=True
    )
)

In [110]:
# add some layout
layout = go.Layout(
    title = "Random values in a scatterplot",
    xaxis_title="X Axis Title",
    yaxis_title="Y Axis Title",
    font=dict(
        family="Courier New, monospace",
        size=12,
        color="Purple"
    )
)

In [111]:
# Combine those into a bar chart
fig = go.Figure(data=trace,layout=layout)

In [112]:
# show the figure
fig

In [113]:
# save the figure as html
fig.write_html("scatter_chart.html")